/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosMDI;

import daos.CategoriaDAO;
import entidades.Categoria;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Frm_MntAdmCat extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_MntAdmiCat
     */
    public Frm_MntAdmCat() {
        initComponents();
        BloquearTabla();
        ListarCategoria();        
    }
    
    public void BloquearTabla(){        
        DefaultTableModel dt = new DefaultTableModel()
                {
                    @Override
                    public boolean isCellEditable(int row, int column)
                        {
                            return false;
                        }
                };        
        tbShowCategoria.setModel(dt);
    }
    int estado;
    int[] listaidCategoria;
    public void ListarCategoria()
        {
        DefaultTableModel dtm=(DefaultTableModel)this.tbShowCategoria.getModel();
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        CategoriaDAO cdao = new CategoriaDAO();
        ArrayList<Categoria> lc = cdao.listarCategoria();
        listaidCategoria = new int[lc.size()];
        String col[] = {"Nombre"};
        dtm.setColumnIdentifiers(col);
        Object[] row = new Object[dtm.getColumnCount()];        
        for (int i = 0; i < lc.size(); i++) {
            listaidCategoria[i] = lc.get(i).getIdCategoria();            
            row[0] = lc.get(i).getNombre();             
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowCategoria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Mantenimiento Categorias");
        setToolTipText("");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        tbShowCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbShowCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowCategoria);

        jLabel1.setText("MANTENIMIENTO CATEGORIAS");

        btnIngresar.setText("AGREGAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("INGRESE NUEVA CATEGORIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE))
        evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void tbShowCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowCategoriaMouseClicked
        int fila = tbShowCategoria.getSelectedRow();
        try
        {
            int id = listaidCategoria[fila];
            Categoria categoria = new Categoria();
            CategoriaDAO cdao = new CategoriaDAO();
            categoria = cdao.buscarEntidad(id);
            txtNombre.setText(categoria.getNombre());
            estado = categoria.getEstado();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_tbShowCategoriaMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usu= txtNombre.getText();
        estado = 1;
        usu=usu.replaceAll(" ", "");
        if(usu.length()==0)
        {
            JOptionPane.showMessageDialog(this,"INGRESE NOMBRE DE CATEGORIA");
        }
        else
        {
            try
            {
                Categoria categoria= new Categoria();
                categoria.setNombre(txtNombre.getText());
                categoria.setEstado(estado);
                CategoriaDAO carDAO = new CategoriaDAO();
                carDAO.crearEntidad(categoria);
                ListarCategoria();
                JOptionPane.showMessageDialog(this,"Se Agrego Exitosamente");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int row = tbShowCategoria.getSelectedRow();
        if (row == -1)
        {
            JOptionPane.showMessageDialog(this,"Seleccione un elemento para poder eliminar");
        }
        else
        {
            try
            {
                int fila = tbShowCategoria.getSelectedRow();
                int id = listaidCategoria[fila];
                CategoriaDAO cdao = new CategoriaDAO();
                cdao.eliminarEntidad(id);
                ListarCategoria();
                JOptionPane.showMessageDialog(this,"Se Elimino Exitosamente");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int row = tbShowCategoria.getSelectedRow();
        if (row == -1)
        {
            JOptionPane.showMessageDialog(this,"Seleccione un elemento para modificar");
        }
        else
        {
            String usu= txtNombre.getText();
            usu=usu.replaceAll(" ", "");
            if(usu.length()==0 )
            {
                JOptionPane.showMessageDialog(this,"INGRESE NOMBRE");
            }
            else
            {
                try
                {
                    int fila = tbShowCategoria.getSelectedRow();
                    int idCategoria = listaidCategoria[fila];
                    Categoria categoria = new Categoria();
                    categoria.setIdCategoria(idCategoria);
                    categoria.setNombre(txtNombre.getText());
                    categoria.setEstado(estado);
                    CategoriaDAO cdao = new CategoriaDAO();
                    cdao.actualizarEntidad(categoria);
                    ListarCategoria();
                    JOptionPane.showMessageDialog(this,"Se Modifico Exitosamente");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbShowCategoria;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
