/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosMDI;

import daos.UsuarioDAO;
import entidades.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Frm_MntoUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_MntoUsuarios
     */
    public Frm_MntoUsuarios() {
        initComponents();
        cargarEstado();
        cargarTipo();
        BloquearTabla();
        ListarUsuario();
    }
    
    public void BloquearTabla(){        
        DefaultTableModel dt = new DefaultTableModel()
                {
                    @Override
                    public boolean isCellEditable(int row, int column){
                    return false;
                }
             };        
        tbShowUsuario.setModel(dt);
    }    
    
    int[] listaEstado;
    public void cargarEstado(){
       cbxEstado.addItem("Activo");
       cbxEstado.addItem("Inactivo");
       listaEstado = new int[2];
       listaEstado[0] = 1;
       listaEstado[1] = 0;
    }    
    
    int[] listaTipo;
    public void cargarTipo(){
       cbxTipo.addItem("Administrador");
       cbxTipo.addItem("Host");
       cbxTipo.addItem("Server");
       listaTipo = new int[3];
       listaTipo[0] = 1;
       listaTipo[1] = 2;
       listaTipo[2] = 3;
    }
    int[] listaidUsuario;
    public void ListarUsuario(){
        DefaultTableModel dtm=(DefaultTableModel)this.tbShowUsuario.getModel();
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        UsuarioDAO pdao = new UsuarioDAO();
        ArrayList<Usuario> lc = pdao.listarEntidad();
        listaidUsuario = new int[lc.size()];
        String col[] = {"IdUsuario","Nombre","Password","Tipo","Estado"};
        dtm.setColumnIdentifiers(col);
        Object[] row = new Object[dtm.getColumnCount()];        
        for (int i = 0; i < lc.size(); i++) {
            listaidUsuario[i] = lc.get(i).getIdUsuario();
            row[0] = lc.get(i).getIdUsuario();
            row[1] = lc.get(i).getUsuario();
            row[2] = lc.get(i).getPassword();
            row[3] = lc.get(i).getTipo();   
            row[4] = lc.get(i).getEstado();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowUsuario = new javax.swing.JTable();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Mantenimiento Usuarios");

        tbShowUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbShowUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowUsuario);

        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });

        jLabel4.setText("TIPO");

        jLabel1.setText("Mantenimientos Usuarios");

        jLabel5.setText("ESTADO ");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("USUARIO");

        jLabel3.setText("PASSWORD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(21, 21, 21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtPassword))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbShowUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowUsuarioMouseClicked
        int fila = tbShowUsuario.getSelectedRow();

        try
        {

            int id = listaidUsuario[fila];
            Usuario usuario = new Usuario();
            UsuarioDAO uDAO = new UsuarioDAO();

            usuario = uDAO.buscarEntidad(id);
            txtUsuario.setText(usuario.getUsuario());
            txtPassword.setText(usuario.getPassword());

            if(listaTipo[0] == usuario.getTipo())
            {
                cbxTipo.setSelectedIndex(0);
            }
            if(listaTipo[1] == usuario.getTipo())
            {
                cbxTipo.setSelectedIndex(1);
            }
            if(listaEstado[0] == usuario.getEstado())
            {
                cbxEstado.setSelectedIndex(0);
            }
            if(listaEstado[1] == usuario.getEstado())
            {
                cbxEstado.setSelectedIndex(1);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_tbShowUsuarioMouseClicked

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        //cargarTipo():
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int index = cbxTipo.getSelectedIndex();
        int tipo = listaTipo[index];
        int index1 = cbxEstado.getSelectedIndex();
        int estado = listaEstado[index1];

        String usu= txtUsuario.getText();
        String pass= txtPassword.getText();
        usu=usu.replaceAll(" ", "");
        pass=pass.replaceAll(" ", "");

        if(usu.length()==0 || pass.length()==0)
        {

            JOptionPane.showMessageDialog(this,"INGRESE DATOS : NOMBRE y/o PASSWORD");
        }
        else
        {
            try
            {
                Usuario usuario= new Usuario();
                usuario.setUsuario(txtUsuario.getText());
                usuario.setPassword(txtPassword.getText());
                usuario.setEstado(estado);
                usuario.setTipo(tipo);
                UsuarioDAO uDAO = new UsuarioDAO();
                uDAO.crearEntidad(usuario);
                ListarUsuario();
                JOptionPane.showMessageDialog(this,"Se Agrego Exitosamente");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int row = tbShowUsuario.getSelectedRow();

        if (row == -1)
        {
            JOptionPane.showMessageDialog(this,"Seleccione un elemento para poder eliminar");
        }
        else
        {
            try
            {
                int fila = tbShowUsuario.getSelectedRow();
                int id = listaidUsuario[fila];
                UsuarioDAO udao = new UsuarioDAO();
                udao.eliminarEntidad(id);
                ListarUsuario();
                JOptionPane.showMessageDialog(this,"Se Elimino Exitosamente");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int row = tbShowUsuario.getSelectedRow();

        if (row == -1)
        {
            JOptionPane.showMessageDialog(this,"Seleccione un elemento para modificar");
        }
        else
        {
            String usu= txtUsuario.getText();
            String pass= txtPassword.getText();
            usu=usu.replaceAll(" ", "");
            pass=pass.replaceAll(" ", "");

            if(usu.length()==0 || pass.length()==0)
            {

                JOptionPane.showMessageDialog(this,"INGRESE DATOS : NOMBRE y/o PASSWORD");
            }
            else
            {
                try{
                    int index = cbxTipo.getSelectedIndex();
                    int tipo = listaTipo[index];
                    int index1 = cbxEstado.getSelectedIndex();
                    int estado = listaEstado[index1];
                    int fila = tbShowUsuario.getSelectedRow();
                    int idUsuario = listaidUsuario[fila];

                    Usuario usuario = new Usuario();
                    usuario.setIdUsuario(idUsuario);
                    usuario.setUsuario(txtUsuario.getText());
                    usuario.setPassword(txtPassword.getText());
                    usuario.setTipo(tipo);
                    usuario.setEstado(estado);

                    UsuarioDAO udao = new UsuarioDAO();
                    udao.actualizarEntidad(usuario);
                    ListarUsuario();
                    JOptionPane.showMessageDialog(this,"Se Modifico Exitosamente");

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbShowUsuario;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
